# Generated by Django 4.2 on 2024-02-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='publish_date',
        ),
    ]
