# Generated by Django 4.2 on 2024-02-16 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='pub_date',
            new_name='publish_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='pub_date',
            new_name='publish_date',
        ),
    ]
