# Generated by Django 4.2 on 2024-02-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
